# Each new term in the Fibonacci sequence is generated by
# adding the previous two terms. By starting with 1 and 2,
# the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose
# values do not exceed four million, find the sum of the even-valued terms.

function fib(n::Int)
    if n==0
        return 0
    end
    f = zeros(Int,n+1)
    f[1] = 0
    f[2] = 1
    for i=3:n+1
        f[i] = f[i-1] + f[i-2]
    end
    return f[n+1]
end

function problem2(Max=4*1e6)
    n = 0
    s = 0.0
    while fib(n)<Max
        if fib(n)%2==0
            s += fib(n)
        end
        n+=1
    end
    return s
end
